import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createFileRoute } from '@tanstack/react-router';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { LineChart } from '@/components/dashboard/charts/LineChart';
import { BarChart } from '@/components/dashboard/charts/BarChart';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
export const Route = createFileRoute('/dashboard/Analytics')({
    component: RouteComponent
});
function RouteComponent() {
    return (_jsxs("div", { className: "container mx-auto p-6", children: [_jsxs("div", { className: "mb-8 flex items-center justify-between", children: [_jsx("h1", { className: "text-2xl font-bold", children: "Analytics" }), _jsxs(Select, { defaultValue: "last30days", children: [_jsx(SelectTrigger, { className: "w-[180px]", children: _jsx(SelectValue, { placeholder: "Select period" }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "last7days", children: "Last 7 days" }), _jsx(SelectItem, { value: "last30days", children: "Last 30 days" }), _jsx(SelectItem, { value: "last90days", children: "Last 90 days" }), _jsx(SelectItem, { value: "lastYear", children: "Last year" }), _jsx(SelectItem, { value: "allTime", children: "All time" })] })] })] }), _jsxs("div", { className: "grid gap-6 md:grid-cols-2", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-base font-medium", children: "Transaction Volume" }) }), _jsx(CardContent, { children: _jsxs(Tabs, { defaultValue: "daily", children: [_jsxs(TabsList, { children: [_jsx(TabsTrigger, { value: "daily", children: "Daily" }), _jsx(TabsTrigger, { value: "weekly", children: "Weekly" }), _jsx(TabsTrigger, { value: "monthly", children: "Monthly" })] }), _jsx(TabsContent, { value: "daily", className: "pt-4", children: _jsx(LineChart, {}) }), _jsx(TabsContent, { value: "weekly", className: "pt-4", children: _jsx(LineChart, {}) }), _jsx(TabsContent, { value: "monthly", className: "pt-4", children: _jsx(LineChart, {}) })] }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-base font-medium", children: "Average Transaction Value" }) }), _jsx(CardContent, { children: _jsxs(Tabs, { defaultValue: "daily", children: [_jsxs(TabsList, { children: [_jsx(TabsTrigger, { value: "daily", children: "Daily" }), _jsx(TabsTrigger, { value: "weekly", children: "Weekly" }), _jsx(TabsTrigger, { value: "monthly", children: "Monthly" })] }), _jsx(TabsContent, { value: "daily", className: "pt-4", children: _jsx(LineChart, {}) }), _jsx(TabsContent, { value: "weekly", className: "pt-4", children: _jsx(LineChart, {}) }), _jsx(TabsContent, { value: "monthly", className: "pt-4", children: _jsx(LineChart, {}) })] }) })] })] }), _jsxs("div", { className: "mt-6 grid gap-6 md:grid-cols-2", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-base font-medium", children: "Transaction Status Distribution" }) }), _jsx(CardContent, { children: _jsx("div", { className: "h-[300px]", children: _jsx(BarChart, {}) }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { className: "text-base font-medium", children: "Mobile Operator Distribution" }) }), _jsx(CardContent, { children: _jsx("div", { className: "h-[300px]", children: _jsx(BarChart, {}) }) })] })] })] }));
}
